% MATLAB Path

newPathEntry = fullfile(getenv('QAL_DIR'), '0_libraries', 'matlab', 'qvl');
pathCell = regexp(path, pathsep, 'split');
if ispc  % Windows is not case-sensitive
  onPath = any(strcmpi(newPathEntry, pathCell));
else
  onPath = any(strcmp(newPathEntry, pathCell));
end

if onPath == 0
    path(path, newPathEntry)
    savepath
end

% Stop RT models
try
    qc_stop_model('tcpip://localhost:17000', 'QCar2_Workspace')
    pause(1)
catch error
end
pause(1)

% QLab connection
qlabs = QuanserInteractiveLabs();
connection_established = qlabs.open('localhost');

if connection_established == false
    disp("Failed to open connection.")
    return
end
disp('Connected')
verbose = true;
num_destroyed = qlabs.destroy_all_spawned_actors();


% Spawn QCar 2
hqcar = QLabsQCar2(qlabs, verbose);
location = [-0.031, 1.311, 0.000];
rotation = [0, 0, -pi/2];
scale = [1,1,1];
hqcar.spawn_id(0,location,rotation,scale,1,true);
hqcar.possess();


% crosswalk
NUMCROSSWALKS = 4;
walks = {};

for i= 1:NUMCROSSWALKS
    walks{i} = QLabsCrosswalk(qlabs, verbose);
end
a = walks{1};
a.spawn_id(0, ...
        [-5, 9.5, 0], ...
        [0,0,pi/2], ...
        [1,1,0.75], ...
        0, ...
       false);

a = walks{2};
a.spawn_id(1, ...
        [1.3, 16, 0],...
        [0,0,0], ...
        [1,1,0.75],...
        0, ...
        false);

a = walks{3};            
a.spawn_id(2, ...
        [7.7, 9.5, 0],...
        [0,0,pi/2], ...
        [1,1,0.75],...
        0, ...
        false);

a = walks{4};
a.spawn_id(3, ...
        [1.3, 3, 0], ...
        [0,0,0], ...
        [1,1,0.75], ...
        0, ...
        false);


% Traffic Light
NUMTRAFFICLIGHTS = 4;
lights = {};
for i=1:NUMTRAFFICLIGHTS

    lights{i} = QLabsTrafficLight(qlabs,verbose);
end 
a=lights{1};
a.spawn_id(0,...
        [-3.77, 13, 0],...
        [0,0,pi/2],...
        [1,1,1],...
        0,...
        true);

a = lights{2};
a.spawn_id(1,...
        [4.9, 14.8, 0],...
        [0,0,0],...
        [1,1,1],...
        0,...
        true);

a = lights{3};
a.spawn_id(2,...
        [6.7, 5.7, 0],...
        [0,0,-pi/2],...
        [1,1,1],...
        0,...
        true);

a = lights{4};
a.spawn_id(3,...
        [-2, 4.27, 0],...
        [0,0,pi],...
        [1,1,1],...
        0,...
        true);


% Yield sign

yieldSigns = QLabsYieldSign(qlabs,verbose);

yieldSigns.spawn([0.4,-13, 0],...
                 [0,0,pi]);


% Roundabout
NUMROUNDABOUTSIGNS = 3;
roundAboutSigns = {};

for i=1:NUMROUNDABOUTSIGNS
    
    roundAboutSigns{i} = QLabsRoundaboutSign(qlabs,verbose);
end


a=roundAboutSigns{1};
a.spawn([24.5,33, 0],...
        [0,0,-pi/2]);

a=roundAboutSigns{2};
a.spawn([4.5,40, 0],...
        [0,0,pi]);

a=roundAboutSigns{3};
a.spawn([10.6,28.5, 0],...
        [0,0,pi]);

% Spawning Basic Shapes
hBasicShape = QLabsBasicShape(qlabs,verbose);

% Plus
hBasicShape.spawn_id_box_walls_from_end_points(2,...
    [-13.64, 3.82, 0.0],...
    [-3.08, -7.062, 0.0],...
    5,...
    3,...
    [(154/255),(101/255),(14/255)],...
    false);

hBasicShape.spawn_id_box_walls_from_end_points(3,...
    [-3.93, 4.00, -0],...
    [-10.034, -3.102, -0],...
    5,...
    3,...
    [(154/255),(101/255),(14/255)],...
    false);

% Roundabout Box
hBasicShape.spawn_id_box_walls_from_end_points(4,...
    [12.104, 38.266, 0],...
    [18.345, 38.433, 0],...
    5,...
    4,...
    [(154/255),(101/255),(14/255)],...
    false);

% Basic Building Box
hBasicShape.spawn_id_box_walls_from_end_points(5,...
[5.969, 0.072, 0.385],...
[16.578, -0.016, 0],...
5,...
8.5,...
[(154/255),(101/255),(14/255)],...
false);


% Spawn stopsign
stop = QLabsStopSign(qlabs,verbose);
stop.spawn([-0.508, -7.327, 0.2],...
            [0,0, pi/2],...
            [1,1,1],...
            0,...
            true);


% Start spawn model
file_workspace = fullfile(getenv('RTMODELS_DIR'), 'QCar2', 'QCar2_Workspace.rt-win64');
pause(2)
system(['quarc_run -D -r -t tcpip://localhost:17000 ', file_workspace]);

qlabs.close()